FROM node:18
ENV NODE_ENV=production
RUN npm install express
RUN npm install dotenv
RUN npm install sequelize
RUN npm install express-validator
RUN npm install bcrypt
RUN npm install body-parser
RUN npm install pg
RUN npm install express-validator --save
RUN npm install cookie-parser
RUN npm install jsonwebtoken
RUN npm install cors
CMD ["npm", "start"]